### PR TITLE
Regenerate index.html file

### PR DESCRIPTION
**Pull request by sideshowbarker**
This is the `index.html` output from running the `index.bs` source through the latest Bikeshed with no options.

---

Bikeshed reports the following:
```
/usr/local/lib/python3.9/site-packages/html5lib/_ihatexml.py:266: DataLossWarning: Coercing non-XML name: https:
  warnings.warn("Coercing non-XML name: %s" % name, DataLossWarning)
LINE ~164: No 'dfn' refs found for 'set a structured header'.
LINE ~195: No 'dfn' refs found for 'set a structured header'.
LINE ~242: No 'dfn' refs found for 'set a structured header'.
LINE ~251: No 'dfn' refs found for 'triggered by user activation'.
LINE ~279: No 'dfn' refs found for 'set a structured header'.
LINE ~288: No 'dfn' refs found for 'triggered by user activation'.
LINE ~291: No 'dfn' refs found for 'triggered by user activation'.
LINE ~306: No 'dfn' refs found for 'triggered by user activation'.
 ✔  Successfully generated, with 8 linking errors
```

### CODE REVIEW

**Comment by sideshowbarker** [comment]
The *Coercing non-XML name: https:* problem was fixed by merging #61.

I can look into fixing the causes of the linking errors.

**Comment by annevk** [comment]
It needs https://fetch.spec.whatwg.org/#concept-header-list-set-structured-header now.

**Comment by sideshowbarker** [comment]
About 'triggered by user activation', I chatted with @annevk about it and looked at https://github.com/whatwg/html/commit/8f8c1f50158736b3cf16188377a0974a20367c8b and at the current HTML spec language, and I can see the change that’d be needed will be more involved. So, leaving that one alone for now.

**Comment by mikewest** [comment]
Closing this, as you've installed the GitHub action. :)

**Pull request closed without merging**
