### PR TITLE
Meta: generate HTML

### PR DESCRIPTION
**Pull request by annevk**

### CODE REVIEW

**Comment by annevk** [comment]
(Making this automatic could be part of that CI project :-))

**Comment by sideshowbarker** [comment]
@annevk Closing this as superseded by #62. (I was gonna instead rebase this to resolve the merge conflict, and push it to here — but it seems the repo this originated from no longer exists, so there’s now no branch to push to here…)

**Comment by sideshowbarker** [comment]
> (Making this automatic could be part of that CI project :-))

I can put time into setting up CI for this repo and any other WebAppSec repos to do autopublishing on every push (and to do anything else we might want to automate)

**Comment by annevk** [comment]
Oops, I guess I need to be more careful when pruning repositories.

**Pull request closed without merging**
